"""Add tax_rate and tax calculations to invoices and quotes

Revision ID: 7eb00a723e1d
Revises: 175573690489
Create Date: 2026-01-29 20:52:51.448206+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb00a723e1d'
down_revision: Union[str, None] = '175573690489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add tax_rate columns as NULLABLE first with default value
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='VAT rate in percentage (e.g., 20.00 for 20%)'))
    op.add_column('invoice_items', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='VAT rate in percentage'))
    op.add_column('quote_items', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='VAT rate in percentage'))
    
    # Update existing rows with default tax rate of 20%
    op.execute("UPDATE products SET tax_rate = 20.00 WHERE tax_rate IS NULL")
    op.execute("UPDATE invoice_items SET tax_rate = 20.00 WHERE tax_rate IS NULL")
    op.execute("UPDATE quote_items SET tax_rate = 20.00 WHERE tax_rate IS NULL")
    
    # Now make tax_rate columns NOT NULL
    op.alter_column('products', 'tax_rate', nullable=False)
    op.alter_column('invoice_items', 'tax_rate', nullable=False)
    op.alter_column('quote_items', 'tax_rate', nullable=False)
    
    # Add subtotal and tax_amount columns as NULLABLE first
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True, comment='Subtotal HT (before tax)'))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Total tax amount'))
    op.add_column('quotes', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True, comment='Subtotal HT (before tax)'))
    op.add_column('quotes', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Total tax amount'))
    
    # Calculate subtotal and tax_amount for existing invoices (assuming 20% tax rate)
    # subtotal = total / 1.20, tax_amount = total - subtotal
    op.execute("""
        UPDATE invoices 
        SET subtotal = ROUND(total / 1.20, 2),
            tax_amount = ROUND(total - (total / 1.20), 2)
        WHERE subtotal IS NULL
    """)
    
    op.execute("""
        UPDATE quotes 
        SET subtotal = ROUND(total / 1.20, 2),
            tax_amount = ROUND(total - (total / 1.20), 2)
        WHERE subtotal IS NULL
    """)
    
    # Now make subtotal and tax_amount columns NOT NULL
    op.alter_column('invoices', 'subtotal', nullable=False)
    op.alter_column('invoices', 'tax_amount', nullable=False)
    op.alter_column('quotes', 'subtotal', nullable=False)
    op.alter_column('quotes', 'tax_amount', nullable=False)
    
    # Update column comments
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Total TTC (with tax)',
               existing_nullable=False)
    op.alter_column('quotes', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Total TTC (with tax)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Total TTC (with tax)',
               existing_nullable=False)
    op.drop_column('quotes', 'tax_amount')
    op.drop_column('quotes', 'subtotal')
    op.drop_column('quote_items', 'tax_rate')
    op.drop_column('products', 'tax_rate')
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Total TTC (with tax)',
               existing_nullable=False)
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoice_items', 'tax_rate')
    # ### end Alembic commands ###

